name: Gatsby Publish # Name of your workflow

on:
  push:
    branches:
      - source # The trigger of the this workflow

jobs:
  build:
    runs-on: ubuntu-latest # Action uses Docker so only Linux is supported
    steps:
      - uses: actions/checkout@v1 # Checkout your triggered branch
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          publishBranch: 'main' # Not required, default publishing branch is master
          deploy-branch: 'gh-pages'
          token: ${{ secrets.PORTFOLIO }} # Your personal access token of GitHub, read more below of how to obtain one and keep it safe
          